from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="CallbackTransaction")


@_attrs_define
class CallbackTransaction:
    """Transaction detail.

    Attributes:
        id (str): Partner unique transaction id to identify the transaction. This is the same
            transaction.id that was sent in the USSD Push request. Example: BBZMiscxy.
        message (str): Description message for the transaction status. Example: Paid RWF 5,000 to TECHNOLOGIES
            LIMITED Charge RWF 140, Trans ID MP210603.1234.L06941.
        status_code (str): Possible Status: TF (Transaction Failed) TS (Transaction Success). Left as a str
            because Airtel may return codes beyond the documented set; see CallbackStatusCode to resolve one.
            Example: TS.
        airtel_money_id (str): Transaction id generated by AM. Example: MP210603.1234.L06941.
    """

    id: str
    message: str
    status_code: str
    airtel_money_id: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        message = self.message

        status_code = self.status_code

        airtel_money_id = self.airtel_money_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "message": message,
                "status_code": status_code,
                "airtel_money_id": airtel_money_id,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        message = d.pop("message")

        status_code = d.pop("status_code")

        airtel_money_id = d.pop("airtel_money_id")

        callback_transaction = cls(
            id=id,
            message=message,
            status_code=status_code,
            airtel_money_id=airtel_money_id,
        )

        callback_transaction.additional_properties = d
        return callback_transaction

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
